repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: conda run -n mdemon isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: conda run -n mdemon black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: conda run -n mdemon flake8
        types: [python]
        exclude: setup.pyW

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: conda run -n mdemon pytest --cov --cov-fail-under=70
        types: [python]
        pass_filenames: false