#!/usr/bin/env python3
"""
MDemon分子质量过滤器

此脚本使用MDemon库读取LAMMPS DATA文件，找到质量小于指定阈值的分子，
然后生成一个新的DATA文件，该文件移除了这些分子中的所有原子。

使用示例:
    python filter_molecules_by_mass.py input.data output.data --mass-threshold 100

    如果有键文件:
    python filter_molecules_by_mass.py input.data output.data --bonds input.reaxff --mass-threshold 100
"""

import argparse
import os
from typing import List, Set, Tuple

import MDemon as md


class LAMMPSDataWriter:
    """用于写入LAMMPS DATA文件的类"""

    def __init__(self, universe: md.Universe):
        self.universe = universe

    def write_filtered_data(self, output_path: str, excluded_atoms: Set[int]):
        """
        写入过滤后的LAMMPS DATA文件

        Parameters:
        -----------
        output_path : str
            输出文件路径
        excluded_atoms : Set[int]
            要排除的原子索引集合
        """
        # 获取需要保留的原子
        all_atom_indices = set(range(len(self.universe.atoms)))
        kept_atom_indices = sorted(all_atom_indices - excluded_atoms)

        print(f"原始原子数量: {len(all_atom_indices)}")
        print(f"排除原子数量: {len(excluded_atoms)}")
        print(f"保留原子数量: {len(kept_atom_indices)}")

        # 创建新的原子ID映射 (旧索引 -> 新ID)
        old_to_new_id = {}
        for new_id, old_idx in enumerate(kept_atom_indices, 1):
            old_to_new_id[old_idx] = new_id

        with open(output_path, "w") as f:
            self._write_header(f, len(kept_atom_indices))
            self._write_masses(f)
            self._write_atoms(f, kept_atom_indices, old_to_new_id)

            # 如果有键信息，写入键
            if hasattr(self.universe, "bonds") and len(self.universe.bonds) > 0:
                self._write_bonds(f, kept_atom_indices, old_to_new_id)

        print(f"✅ 新的DATA文件已写入: {output_path}")

    def _write_header(self, f, n_atoms: int):
        """写入文件头"""
        f.write(
            "# Filtered LAMMPS data file - molecules with mass < threshold removed\n"
        )
        f.write("# Generated by MDemon filter_molecules_by_mass.py\n\n")

        f.write(f"{n_atoms} atoms\n")

        # 获取原子类型数量
        atom_types = set(
            self.universe.atoms[i].species for i in range(len(self.universe.atoms))
        )
        f.write(f"{len(atom_types)} atom types\n")

        # 写入盒子信息
        box = self.universe.box
        f.write(f"\n{box[6]:.10f} {box[7]:.10f} xlo xhi\n")
        f.write(f"{box[8]:.10f} {box[9]:.10f} ylo yhi\n")
        f.write(f"{box[10]:.10f} {box[11]:.10f} zlo zhi\n\n")

    def _write_masses(self, f):
        """写入质量信息"""
        f.write("Masses\n\n")

        # 获取所有原子类型及其质量
        type_mass_map = {}
        for atom in self.universe.atoms:
            atom_type = atom.species
            if atom_type not in type_mass_map:
                type_mass_map[atom_type] = atom.mass

        for atom_type in sorted(type_mass_map.keys()):
            f.write(f"{atom_type} {type_mass_map[atom_type]:.5f}\n")
        f.write("\n")

    def _write_atoms(self, f, kept_atom_indices: List[int], old_to_new_id: dict):
        """写入原子信息"""
        f.write("Atoms # full\n\n")

        for old_idx in kept_atom_indices:
            atom = self.universe.atoms[old_idx]
            new_atom_id = old_to_new_id[old_idx]

            # 获取分子ID (使用原子的分子索引)
            if hasattr(atom, "mle_top") and atom.mle_top:
                # mle_top是一个字典，键是分子索引
                mol_id = list(atom.mle_top.keys())[0] + 1
            else:
                mol_id = 1

            # 获取原子属性
            atom_type = atom.species
            charge = atom.charge if hasattr(atom, "charge") else 0.0
            x, y, z = atom.coordinate

            f.write(
                f"{new_atom_id} {mol_id} {atom_type} {charge:.10f} "
                f"{x:.10f} {y:.10f} {z:.10f}\n"
            )
        f.write("\n")

    def _write_bonds(self, f, kept_atom_indices: List[int], old_to_new_id: dict):
        """写入键信息"""
        kept_atom_set = set(kept_atom_indices)
        valid_bonds = []

        # 找到所有有效的键（两个原子都被保留）
        for bond in self.universe.bonds:
            atoms_in_bond = list(bond.atm_top)
            if len(atoms_in_bond) >= 2:
                atom1_idx, atom2_idx = atoms_in_bond[0], atoms_in_bond[1]
                if atom1_idx in kept_atom_set and atom2_idx in kept_atom_set:
                    # 转换为新的原子ID
                    new_atom1_id = old_to_new_id[atom1_idx]
                    new_atom2_id = old_to_new_id[atom2_idx]
                    bond_type = bond.species if hasattr(bond, "species") else 1
                    valid_bonds.append((bond_type, new_atom1_id, new_atom2_id))

        if valid_bonds:
            f.write("Bonds\n\n")
            for i, (bond_type, atom1_id, atom2_id) in enumerate(valid_bonds, 1):
                f.write(f"{i} {bond_type} {atom1_id} {atom2_id}\n")
            f.write("\n")


def find_small_molecules(
    universe: md.Universe, mass_threshold: float
) -> Tuple[List[int], Set[int]]:
    """
    找到质量小于阈值的分子及其包含的原子

    Parameters:
    -----------
    universe : md.Universe
        MDemon Universe对象
    mass_threshold : float
        质量阈值

    Returns:
    --------
    small_molecules : List[int]
        质量小于阈值的分子索引列表
    atoms_to_exclude : Set[int]
        需要排除的原子索引集合
    """
    small_molecules = []
    atoms_to_exclude = set()

    print(f"🔍 查找质量小于 {mass_threshold} 的分子...")
    print(f"总分子数量: {len(universe.molecules)}")

    for i, molecule in enumerate(universe.molecules):
        mol_mass = molecule.mass

        if mol_mass < mass_threshold:
            small_molecules.append(i)
            # 获取这个分子包含的所有原子索引
            atom_indices = molecule.atms
            atoms_to_exclude.update(atom_indices)
            print(f"  分子 {i}: 质量 = {mol_mass:.2f}, 原子数量 = {len(atom_indices)}")

    print("\n📊 统计结果:")
    print(f"  质量小于 {mass_threshold} 的分子数量: {len(small_molecules)}")
    print(f"  需要移除的原子总数: {len(atoms_to_exclude)}")

    return small_molecules, atoms_to_exclude


def main():
    parser = argparse.ArgumentParser(description="过滤分子并生成新的LAMMPS DATA文件")
    parser.add_argument("input_data", help="输入的LAMMPS DATA文件路径")
    parser.add_argument("output_data", help="输出的LAMMPS DATA文件路径")
    parser.add_argument("--bonds", help="可选的键文件路径（如.reaxff文件）")
    parser.add_argument(
        "--mass-threshold",
        type=float,
        default=100.0,
        help="分子质量阈值（默认: 100.0）",
    )

    args = parser.parse_args()

    # 检查输入文件是否存在
    if not os.path.exists(args.input_data):
        print(f"❌ 错误: 输入文件不存在: {args.input_data}")
        return

    if args.bonds and not os.path.exists(args.bonds):
        print(f"❌ 错误: 键文件不存在: {args.bonds}")
        return

    print(f"📁 输入文件: {args.input_data}")
    if args.bonds:
        print(f"📁 键文件: {args.bonds}")
    print(f"📁 输出文件: {args.output_data}")
    print(f"⚖️  质量阈值: {args.mass_threshold}")
    print()

    try:
        # 创建Universe对象
        print("📖 读取输入文件...")
        if args.bonds:
            universe = md.Universe(args.input_data, args.bonds)
        else:
            universe = md.Universe(args.input_data)

        print("✅ 成功读取Universe")
        print(f"   原子数量: {len(universe.atoms)}")
        print(f"   分子数量: {len(universe.molecules)}")
        if hasattr(universe, "bonds"):
            print(f"   键数量: {len(universe.bonds)}")
        print()

        # 找到质量小的分子
        small_molecules, atoms_to_exclude = find_small_molecules(
            universe, args.mass_threshold
        )

        if not small_molecules:
            print(f"✅ 没有找到质量小于 {args.mass_threshold} 的分子")
            print("🔄 复制原始文件到输出路径...")
            import shutil

            shutil.copy2(args.input_data, args.output_data)
            print(f"✅ 完成: {args.output_data}")
            return

        # 写入新的data文件
        print("\n💾 写入过滤后的文件...")
        writer = LAMMPSDataWriter(universe)
        writer.write_filtered_data(args.output_data, atoms_to_exclude)

        print(f"\n🎉 完成！过滤后的文件已保存到: {args.output_data}")

    except Exception as e:
        print(f"❌ 错误: {e}")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    main()
